djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from leads.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leads.urls', namespace='leads')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from . views import *

app_name = 'leads'

urlpatterns = [
    path('', HomepageView.as_view(), name="home_page"),
    path('leads/', LeadHomepageView.as_view(), name="lead_page"),
    path('lead/<int:pk>', LeadDetailsPageView.as_view(), name="lead_details"),
    path('leads/create', CreateLeadsView.as_view(), name="create_leads"),
    path('lead/edit/<int:pk>', LeadUpdateView.as_view(), name="Update-leads"),
    path('agents', Agents, name="agents"),
    path('agent/<int:pk>', Agent_details, name="agent_details"),
    path('agent/edit/<int:pk>', AgentUpdateView.as_view(), name="agent_update"),
    path('agents/create', Create_agent_p, name="agent_create"),
    path('agent/delete/<int:pk>', AgentDeleteView.as_view(), name="Agent_delete"),
    path('user/create', CreateUserView.as_view(), name="create_user"),
    path('bd', BangladeshView.as_view())


] 

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

class Agent(models.Model):
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Leads(models.Model):
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    age = models.IntegerField(null=True, blank=True)
    agent = models.ForeignKey("Agent", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} | Agent : {self.agent}"

leads/forms.py
from django import forms
from django.db.models import fields
from .models import *
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ("username",)
        field_classes = {'username': UsernameField}

class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'password',
            'email'
        )


class LeadModelform(forms.ModelForm):
    class Meta:
        model = Leads
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
        )

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = Agent
        fields= (
            'first_name',
            'last_name',
            'user'
        )
class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Leads
        fields = (
            'first_name',
            'last_name',
            'age'
        )

class Leadform(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)


class CreateAgentModelForm(forms.ModelForm):
    class Meta:
        model = Agent
        fields = (
            'first_name',
            'last_name',
            'user'
        )

leads/views.py
from django.http import request
from django.shortcuts import render, redirect, reverse
from django.views import generic
from . models import *
from . forms import *
 
class BangladeshView(generic.TemplateView):
	template_name = 'lead/bangladesh.html'

class SignupView(generic.CreateView):
	template_name = 'registration/signup.html'
	form_class = CustomUserCreationForm

	def get_success_url(self):
		return reverse('login')

class HomepageView(generic.TemplateView):
	template_name = "site-home.html"


class LeadHomepageView(generic.ListView):
	template_name = "lead/home.html"
	queryset = Leads.objects.all()
	context_object_name = "leads"

class LeadDetailsPageView(generic.DetailView):
	template_name = "lead/details.html"
	queryset = Leads.objects.all()
	context_object_name = 'lead'


class CreateLeadsView(generic.CreateView):
	template_name = 'lead/create.html'
	form_class = LeadModelform
	context_object_name = 'form'

	def get_success_url(self):
		return reverse("leads:lead_page")

class LeadUpdateView(generic.UpdateView):
	template_name = 'lead/create.html'
	form_class = LeadModelForm
	context_object_name = 'lead'

	def get_success_url(self):
		return reverse("leads:lead_page")


class CreateUserView(generic.CreateView):
	template_name = 'lead/create-user.html'
	form_class = UserModelForm

	def get_success_url(self):
		return reverse("leads:lead_page")

class DeleteUserView(generic.DeleteView):
	x = 10

class AgentUpdateView(generic.UpdateView):
	template_name = 'lead/agent-update.html'
	queryset = Agent.objects.all()
	form_class = LeadModelForm
	context_object_name = 'agent'

	def get_success_url(self):
		return reverse("leads:agents")

class AgentDeleteView(generic.DeleteView):
	template_name = 'lead/delete-agent.html'
	queryset = Agent.objects.all()

	def get_success_url(self):
		return reverse("leads:agents")


class TestView(generic.TemplateView):
	template_name = 'lead/test.html'

def UpdateLead(request, pk):
	lead = Leads.objects.get(id=pk)
	form = LeadModelForm(instance=lead)

	if request.method == 'POST':
		form = LeadModelForm(request.POST, instance=lead)
		if form.is_valid:
			form.save()
		return redirect("/leads")
	context = {
		"form" : form
	}
	return render(request, "lead/update-leads.html", context)

def Agents(request):
	agents = Agent.objects.all()
	context = {
		"agents":agents
	}
	return render(request, "lead/agents.html", context)

def Create_agent_p(request):
	form = CreateAgentModelForm()
	
	if request.method == "POST":
		form = CreateAgentModelForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/agents')

	context = {
		"form": form
	}
	return render(request, "lead/create-agents.html", context)

def Agent_details(request, pk):
	agent = Agent.objects.get(pk=pk)
	context = {
		"agent": agent
	}
	return render(request, "lead/agent-details.html", context)

def Agent_update(request, pk):
	agent = Agent.objects.get(id=pk)
	form = AgentModelForm(instance=agent)

	if request.method == "POST":
		form = AgentModelForm(request.POST, instance=agent)
		if form.is_valid:
			form.save()
			return redirect('/agents')
	context = {
		"agent": agent,
		"form" :form
	}

	return render(request, "lead/agent-update.html", context)

def Delete_agent_p(request, pk):
	Agent.objects.get(id=pk).delete()
	return redirect('/agents')
	

leads/templates/lead/agent-details.html
{% extends "base.html" %}
{% block content %}
<h1>Agents</h1>
<ul>               
    <li>
        <div>Person: {{agent.first_name}} {{agent.last_name}}</div><hr>
        <div>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Hic blanditiis recusandae, aliquid reprehenderit ut 
                veritatis dignissimos sapiente accusamus explicabo magnam atque! 
                Accusantium nesciunt quaerat esse ut et numquam ad est!</p>
        </div>
        <div>
            <a href="/agent/edit/{{agent.id}}">Edit</a><br>
            <a href="/agent/delete/{{agent.id}}">Delete</a>
        </div>
    </li>
</ul>
{% endblock %}

leads/templates/lead/agent-update.html
{% extends "base.html" %}
{% block content %}
    <h1>Update agent : <b>{{agent.first_name}} {{agent.last_name}}</b></h1>
    <div>
        <form method="post" action="">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Update agent</button>
        </form>
    </div>

{% endblock %} 

leads/templates/lead/agents.html
{% extends "base.html" %}
{% block content %}
<h1>Agents</h1>
<ul>
    {% for a in agents %}
    <li>
        <div><a href="{% url 'leads:agent_details' a.id %}">Person: {{a.first_name}} {{a.last_name}}</a></div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

leads/templates/lead/bangladesh.html
<!doctype html>
<html lang="en">
  <head>
    <title>Bangaldesh</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
      <h1>This is a test page from Bangladesh</h1>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

leads/templates/lead/create-agents.html
{% extends "base.html" %}
{% block content %}
<h1>Create agents</h1>
<div>
    <form method="post" action="">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Create agent</button>
    </form>
</div>
{% endblock %}

leads/templates/lead/create-user.html
{% extends "base.html" %}
{% block content %}
<h1>Create User</h1>
<div>
    <form method="post" action="">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Create User</button>
    </form>
</div>
{% endblock %}

leads/templates/lead/create.html
{% extends "base.html" %}
{% block content %}

<h4>Lead home page</h4>
<hr class="text-secondary mb-4">

<div class="row">
        <h1>Create new lead here</h1>
        <form method="post" action="">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Create entry</button>
        </form>
    </div>


    {% endblock %}

leads/templates/lead/delete-agent.html
{% extends "base.html" %}
{% block content %}
<h1>Are you sure you want to delete this agent</h1>
<div>
    <form method="post" action="">
        {% csrf_token %}
        <button type="submit">Delete agent</button>
    </form>
</div>
{% endblock %}

leads/templates/lead/details.html
{% extends "base.html" %}
{% block content %}
<h1>Lead details page</h1>
<ul>          
    <li>
        <div>Person: {{lead.first_name}} {{lead.last_name}}</div>
        <div>Age: {{lead.age}}</div>
        <div>Agent: {{lead.agent}}</div>
    </li>
</ul>
{% endblock %}

leads/templates/lead/home.html
{% extends "base.html" %}
{% block content %}

<h4>Lead home page</h4>
<hr class="text-secondary mb-4">

<div class="row">
    {% for l in leads %}
    <div class="col-sm-4">
        <div class="border rounded mb-4 p-3 bg-light">
                <a href="{% url 'leads:lead_details' l.id %}"><h6> {{l.first_name}} {{l.last_name}}</h6></a>
                <p >Lorem ipsum dolor, sit amet consectetur adipisicing elit. </p>
                <p><b class="text-primary">Age : </b>{{l.age}} &nbsp;
                <b class="text-primary">Agent : </b>{{l.agent}}</p>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

leads/templates/lead/nav.html
{% load static %}
<header class="p-2 bg-white border">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-decoration-none">
          <img src="{% static 'img/logo.gif' %}">
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'leads:create_user' %}" class="nav-link px-2">Create user</a></li>
          <li>
              <a href="{% url 'leads:lead_page' %}" class="nav-link px-2 dropdown-toggle" data-bs-toggle="dropdown">
                Leads
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'leads:lead_page' %}">Leads</a></li>
                <li><a class="dropdown-item" href="{% url 'leads:create_leads' %}">Create Leads</a></li>
              </ul>
          </li>
          <li>
            <a href="{% url 'leads:agents' %}" class="nav-link px-2 dropdown-toggle" data-bs-toggle="dropdown">
              Agents
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'leads:agents' %}">Agent</a></li>
              <li><a class="dropdown-item" href="{% url 'leads:agent_create' %}">Create agent</a></li>
            </ul>
        </li>
        <li>
          <a href="{% url 'leads:agents' %}" class="nav-link px-2 dropdown-toggle" data-bs-toggle="dropdown">
            User
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'leads:agent_create' %}">Users</a></li>
            <li><a class="dropdown-item" href="{% url 'leads:create_user' %}">Create user</a></li>
          </ul>
        </li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>
    {% if request.user.is_authenticated %}
    <div class="text-end">
      <span>Hello {{request.user.username.upper}}</span>
      <a class="btn btn-warning " href="{% url 'logout'%}">Logout</a>
    </div>
    {% else %}
    <div class="text-end">
      <a  href="{% url 'login' %}" class="btn btn-outline-dark me-2">Login</a>
      <a href="{% url 'signup' %}" class="btn btn-warning">Sign-up</a>
    </div>

    {% endif %}

      </div>
    </div>
  </header>

leads/templates/lead/test.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
  
    


    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

leads/templates/lead/update-leads.html
{% extends "base.html" %}
{% block content %}
<div class="body">
    <h1>Update lead : <b>{{lead.first_name}} {{lead.last_name}}</b></h1>
    <div>
        <form method="post" action="">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Update lead</button>
        </form>
    </div>
</div>
{% endblock %} 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Listed agents</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    {% include "lead/style.css" %}
 <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" crossorigin="anonymous"></script>   
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>   
<link rel="stylesheet" href="https://getbootstrap.com/docs/5.1/dist/css/bootstrap.min.css">

</head>

<body>
    <div class="container" style="max-width: 1000px;">
        {% include "lead/nav.html" %}


        <div class="mt-4 border rounded p-3">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>

</html>

templates/site-home.html
{% extends "base.html" %}
{% block content %}

<div class="body">
<h1>Site main home page</h1>
</div>

{% endblock %}